### ISSUE TITLE
hardware button back pressed geeft oude data weer wanner taak is updatet

### ISSUE THREAD

**Issue by Patrick-Batenburg** [Patrick-Batenburg/WindowsPhoneApp#14]
`Frame.BackStack.RemoveAt(Frame.BackStack.Count - 1);` 
en/of
```csharp
if (e.NavigationMode == NavigationMode.Back)
{
    //
}
```
laat de laatste navigatie in de stack verwijderen, dit zal als het goed is `typeoff(EditPage)` wanneer user weg van deze view nagigeert, bijvoordbeeld door cancel button of de hardware back button.
in app.cs check in de hardwarebutton_pressed event wanneer de user zich in editpage bevindt `typeoff(EditPage)` dan doe de user altijdt naar de listview redirecten `typeoff(StartPage)`

**Comment by ppowersteef** [comment]
Fixed it
