### ISSUE TITLE
EditPage geeft displaymessagebox weer wanneer men enkele velden met hun oude data laat

### ISSUE THREAD

**Issue by Patrick-Batenburg** [Patrick-Batenburg/WindowsPhoneApp#15]
dit gedrag hoort niet te voorkomen als alle velden al ingevuld zijn.

**Comment by ppowersteef** [comment]
Issue fixed! 
Het word nu direct gecontroleerd wanneer er op de opslaan button word geklikt. de functie van het roodmaken van de velden is nu wel weg.
